### PR TITLE
move webapp to geppetto-client and extension to geppetto-application

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
- The content of webapp folder was moved to [geppetto-client](https://github.com/openworm/geppetto-client).
- The content of extensions folder was moved to [geppetto-application](https://github.com/openworm/geppetto-application).
- geppetto-application is now responsable for bundling the files.
- geppetto-application is now requiring geppetto-client in package.json (the npm package name is @geppettoengine/geppetto-client).
- geppetto-client can be installed in development mode by:
```
1 - cloning geppetto-client repo
2 - run npm install  in geppetto-client 
3 - run npm link in geppetto-client    <-- create a symlink to global node_modules folder
4 - navigate to geppetto-application
4 - run npm link @geppettoengine/geppetto-client  <-- creates a symlink from global node_modules folder to geppetto-application node_modules folder
```
- Travis-ci yml file was moved to geppetto-application
- Test files were moved to geppetto-application
- org.geppetto  dockerfiles (geppetto, livegeppetto, and persistence-geppetto) were refactored. In particular, a new dockerhub image containing java8, maven and virgo (available [here](https://github.com/MetaCell/java-virgo-maven) or [here](https://hub.docker.com/r/metacell/java-virgo-maven)) was factored out, and we are reducing docker image size.
- Linting was applied to geppetto-application and geppetto-client.
- Now lint will run automatically on `npm run build`, `buld-dev`, `build-dev-noTest`, and `build-dev-noTest:watch`. If linting errors are found, the build won't proceed.
- Linting rules for geppetto-application areautomatically read from geppetto-client. If extra rules are required, only the extra rules need to be written in `.eslintrc.js`.
- The following packages were removed from package.json:
```
"aws-sdk": "^2.108.0",
"image-webpack-loader": "^2.0.0",
"jquery.cookie": "^1.4.1",
"jsx": "^0.9.89",
"lg-autoplay": "^1.0.4",
"lg-zoom": "^1.1.0",
"lodash.clone": "^4.5.0",
"react-at-rest": "2.0.11",
"react-autosuggest": "^9.3.2",
"react-collapsible": "^2.3.1",
"react-drag-and-drop": "2.4.0",
"react-router": "^4.1.1",
"react-router-dom": "^4.1.1",
"react-simpletabs": "0.7.0",
"react-tap-event-plugin": "^2.0.1",
"three-loaders-collada": "^1.0.1",
```
- New geppetto applications can use geppetto-application as a template to build custom apps (lint will also run automatically. To disable it, remove `.eslint.rc.js`). The process should be straightforward :taco::

```
📁 geppetto-application/ComponentInitialization.js 

global.jQuery = require("jquery");
global.GEPPETTO_CONFIGURATION = require('./GeppettoConfiguration.json'); ◀️  bring some configs

jQuery(function () {
  require('geppetto-client-initialization');   ◀️  initialize geppetto
  { .... }   ◀️ start writing your app here
```
- Optionally you can install ESlint vscode plugin to have eslint highlighting the code without having to run `npm run build`
- `NPM` and `node` versions had to be upgraded in `org.geppetto.frontend` `pom.xml` to run `eslint`
- Some options in `GeppettoConfiguration.json` don't exist anymore. In particular `extensions` key. 
- ⚠️ If you are running an `install.py` script to clone `org.geppetto.frontend` and install your app, remember to remove the step where you replace the default `GeppettoConfiguration.json` file that comes with `org.geppetto.frontend/src/main/webapp`.

### CODE REVIEW

**Comment by tarelli** [comment]
Test

**Comment by tarelli** [comment]
Test

**Comment by tarelli** [comment]
Test

**Comment by rodriguez-facundo** [comment]
> Test

??

**Comment by tarelli** [comment]
I was testing notifications

**Comment by tarelli** [comment]
@rodriguez-facundo Superb job! Both mvn install (using whatever is pushed on npm) and development command works. I have errors though when I use the development version, screenshot:
screenshot 2019-03-04 at 16 59 23
Any idea about that?

**Comment by rodriguez-facundo** [comment]
@tarelli I can't reproduce this error. 
react-dnd was updated recently and that was triggering an error in the logs. I fixed that by locking react-dnd version to 7.0.2 instead of 7.1.0

Screen Shot 2019-03-11 at 11 56 47

The error above the console is due to `data-rowType` and `data-experimentId`

**Comment by tarelli** [comment]
@rodriguez-facundo thanks for looking into that! @ddelpiano useful piece of information for you as you  start porting vfb to the new structure. I'll wait confirmation from Dario before merging this. Great stuff again Facu :)

**Comment by tarelli** [comment]
@tarelli as a reminder before releasing we need to remove the infra-merge branch from the package.json of geppetto-application and remove the "rm" of webapp in setup.py

**Comment by ddelpiano** [comment]
@tarelli @rodriguez-facundo this does not work properly for me testing it under my linux ubuntu machine (another update will follow regarding the testing with macos).

Note that I tested this with the extension geppetto-vfb that has been merged with geppetto-application, but also with the standard geppetto-application and the sympthoms are somehow very similar even if with geppetto-vfb I don't see the UI at all (but I think it's just a consequence of the first problem).
Procedure that I follow to deploy this locally:
- using the current deployment that I have (all the bundles on development branch and updated to the latest release 0.4.2), I move into org.geppetto.frontend/src/main/webapp and I purged completely the content of this folder (hidden files as well).
- Once the webapp folder is clean, I clone here the geppetto-application repo, I move inside it and I move all the content of this one level up (inside webapp) with "cp -r * ../; cp -r .* ../;"
- I move back to the root level of org.geppetto.frontend and I run "mvn -Dhttps.protocols=TLSv1.2 clean install".
- I move into ~/git/geppetto-sources/org.geppetto/utilities/source_setup and I run "python update_server.py", in order to update the server's deployment (note, I ran also the new script to update the frontend, that did not help).

- Start virgo
- Start npm with "npm start" from the webapp folder.

Once done, from either 8080 or 8081 ports it seems that some of the files are not exposed from webpack.

Since I first tried to use the geppetto-client downloaded directly from npm and that did not work very well I also tried to clone the geppetto-client (first outside, then inside the webapp folders, tried in different attempts) and link this with the local node_modules (tested it adding a bogus file inside the folder to see if I was loading the right version), that did not help as well.

geppetto (2)

Screenshot from 2019-03-19 19-33-36

**Comment by rodriguez-facundo** [comment]
Hi @dario, can you use `infra-merge` for org.geppetto.frontend. I did some changes to that repo also. In particular, pom.xml is important for `mvn install` (or maybe you already changed that and was not mentioned?)

**Comment by ddelpiano** [comment]
issue resolved, misconfiguration in the pom.xml, it works fine. Good news for @tarelli, I did not see the error you saw in console (as Facu).

**Comment by tarelli** [comment]
Great news!

**Comment by tarelli** [comment]
@rodriguez-facundo can you update [this page](https://github.com/openworm/org.geppetto.docs/blob/master/source/build.md) to reflect the philosophy behind all these changes and how to create a Geppetto application before we merge this?

**Comment by rodriguez-facundo** [comment]
I'm on it

**Pull request merged**
