### PR TITLE
Form Dialog Widget

### PR DESCRIPTION
**Pull request by adrianq**

### CODE REVIEW

**Comment by tarelli** [comment]
@adrianq I really like the idea of a form, especially an easily configurable one like this! One thought that I have though is that widgets are meant as way for users to view the data, say a user wants to plot some data and there is a widget for that, a user wants to look at connectivity and there is a widget for that, etc.. Is the user ever going to say I need a form? It's more something that it might be made available in one or multiple deployments and configured for the users to use it but in that case would a react component be more appropriate? Basically same as we have chosen for both the search and the control panel. What do you think? cc @gidili

**Comment by adrianq** [comment]
@tarelli @gidili Yes, I have also thought about this. Actually, if you look to my commits I firstly implemented something like a FormWidget and a SimulatorFormWidget (that extends FormWidget). I was thinking to do this because I didn't want to keep adding stuff to the js geppetto script but it has also to do with the idea of this Form Widget becoming a base 'thing' (component?) that can be extended in a more elegant way. If we go for the react component approach, how can the component be customised depending on the geppetto instance? A set of javascripts file in a folder? (I am not an expert on react components). On the other hand, we discussed a little bit about having a 'Import js library' feature instead of the js geppetto script, can these two tasks be related somehow and attempt to solve the two problems at once? Regarding this PR, what if you merge it and we try to refactor the code for the next release once I am back from holidays? I am also up for a quick hangout tomorrow morning (San Diego time) if you want to....

**Comment by gidili** [comment]
@adrianq this is an example of [react components we have for wormsim](https://github.com/openworm/org.wormsim.frontend/tree/master/src/main/webapp/js/components/dev), basically they get copied together with [this configuration file](https://github.com/openworm/org.wormsim.frontend/blob/master/src/main/webapp/js/components/components.js) in the js/components/dev folder during deployment. That config.js controls which components show up in Geppetto. [This](https://github.com/openworm/org.wormsim.frontend/blob/master/utilities/deployWormSimComponents.py) is the script that does the copying for wormsim. These custom components are not dissimilar from the spotlight and the control panel, but those will be included by default if that config.js is not edited because they are generic. 

I like the form widget a lot too btw - it's going to be massively useful!

**Comment by adrianq** [comment]
@gidilli I have just had a quick look and it looks good and easy and definitively I agree that it probably makes more sense to be a component instead of a widget. Question: Would it still fit the idea of the compulsoryActions in the Geppetto.Flow? Can we do sth like 'showComponent' or 'createComponent'? I guess so but just to be sure...
Unfortunately, I do not think I will have time to refactor it into a component before hols. If you guys want to give it a try (should be straight forward). It can potentially be an interesting, easy and very well define task for a contributor too. Otherwise, I will take care of this once I am back...

**Comment by gidili** [comment]
@adrianq I think it should be fine, you can do pretty much anything you want in a component - for example in some of the wormsim ones we are overriding the THREE.js renderer (so that it can animate meshes), while in others we are simply defining a new simulation controls bar and in others just exposing configuration for the wormsim button bar widgets. I think the refactoring is going to take some thinking in terms of how the user brings up the component though, right now there's only one instance of a component if you include it in the config.js file, while you want to retain the option to potentially have multiple forms. Maybe wait and when you're back from holidays (and I am too!) we can discuss options.

**Comment by adrianq** [comment]
@tarelli @gidili I have renamed this branch as it is not about nsg anymore. I will create a new PR from [here](https://github.com/openworm/org.geppetto.frontend/tree/components)

**Pull request closed without merging**
