### PR TITLE
connectivity matrix pre/post pop indicators

### PR DESCRIPTION
**Pull request by mattearnshaw**
- [x] Run [CoreTests.js Casper Tests](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/pages/tests/casperjs/README.md), make sure they all pass, attach screenshot
- [x] Run [UITests.js Casper Tests](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/pages/tests/casperjs/README.md), make sure they all pass, attach screenshot
- [x] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

cf. https://github.com/OpenSourceBrain/geppetto-osb/issues/48

either this should be merged after https://github.com/openworm/org.geppetto.frontend/pull/623 since it is based on the head of that, or just ignore that and just work with this one. also the UITest updates requires https://github.com/openworm/org.geppetto.persistence/pull/46.

(these are technically PASS)
core
ui

### CODE REVIEW

**Comment by borismarin** [comment]
@mattearnshaw 👏

**Comment by mattearnshaw** [comment]
@tarelli I have a known bug to fix with this, will let you know when it's ready

**Comment by mattearnshaw** [comment]
@tarelli ok, this should be fine. if you find it easier https://github.com/openworm/org.geppetto.frontend/pull/623 could be reviewed and merged first which would cut down the diff for this

**Comment by tarelli** [comment]
@mattearnshaw hey Matt, using matrix-pre-post for frontend, geppetto default extension, loading sample 5 I get the errors below, am I missing something?
screen shot 2017-07-03 at 14 16 25

**Comment by mattearnshaw** [comment]
@tarelli ah whoops, `connectivity-colors` branch of geppetto-osb is also required...

**Comment by mattearnshaw** [comment]
`setData` has some new parameters, which I have started to describe here https://github.com/openworm/org.geppetto.docs/commit/2d5b80dd6a8181590c44651a07254f99e34ad055

I guess parts of the default extension will need updating too

**Comment by tarelli** [comment]
@mattearnshaw but it has to work also with the default extension :) What is the change that is required?

**Comment by tarelli** [comment]
@mattearnshaw it's probably something here though https://github.com/openworm/org.geppetto.core/blob/development/src/main/resources/projects/AuditoryCortex/5.json#L78 the default configuration doesn't do anything specific regarding the connectivity. Can the implementation be robust so that loading a pre-saved view (this is just an example, it could be on anybody's machine/db) would still work? Some kind of default sub-optimal behaviour.

**Comment by mattearnshaw** [comment]
@tarelli it should be a simple matter of adding an extra line to that json, in the "options" field, I'll get back to you

**Comment by tarelli** [comment]
@mattearnshaw I know but the thing to think about is that in general we can't update the views so it's better if whatever changes we make at the API level can avoid breaking backward compatibility with pre-existing views.

**Comment by mattearnshaw** [comment]
@tarelli would it be acceptable to fall back on the neuroml library as a default?

**Comment by tarelli** [comment]
@mattearnshaw what's the NeuroML library? If you can sum up what changed and how the view would have to change I can help you brainstorming to find a solution.

**Comment by mattearnshaw** [comment]
@tarelli I mean `GEPPETTO.ModelFactory.geppettoModel.neuroml`

the view has one mandatory new field, `library`, which was to factor out hardcoded references to neuroml. but it needs to be something that has `network` and `connection` keys (such as  `GEPPETTO.ModelFactory.geppettoModel.neuroml`)

**Comment by mattearnshaw** [comment]
@tarelli, this does the job, for example https://github.com/openworm/org.geppetto.frontend/pull/626/commits/9e0dfb3bc43996f26db46ae96b9377ac9a23b574

**Comment by mattearnshaw** [comment]
eliminate `library` parameter by:
- [ ] add connection to geppetto common library
- [ ] set neuroml.connection supertype to common library `connection` etc.

**Comment by mattearnshaw** [comment]
@tarelli btw i think this is finally ready when you have a chance. requires: https://github.com/openworm/org.geppetto.core/pull/134

**Comment by tarelli** [comment]
@mattearnshaw when I click on a square I get this, is it the same for you?
screen shot 2017-07-11 at 10 26 31
Also how long does it take for you to load the acnet2 sample project (id 5)?

**Comment by tarelli** [comment]
@mattearnshaw also none of the other layouts seem to work anymore?

screen shot 2017-07-11 at 10 37 31

**Comment by mattearnshaw** [comment]
@tarelli what command are you using to add the different layouts? I've found a bug but the error is different. and yes, I get the same thing with clicking a square, will push fix

**Comment by mattearnshaw** [comment]
@tarelli dw, have replicated. will let you know when it's good

**Comment by tarelli** [comment]
@mattearnshaw I click on the gear icon on the top bar or the connectivity
widget and use the UI

**Comment by mattearnshaw** [comment]
@tarelli the UI config function is looking for a network type in the (common) library so it can get the top level object. is there an agnostic way to get the top level object?

**Comment by mattearnshaw** [comment]
@tarelli alright, ready to try again. if you wish to test also with geppetto-osb, please pull its `connectivity-colors` branch

**Pull request merged**
