### PR TITLE
Absolute camera movement.

### PR DESCRIPTION
**Pull request by felipetavares**
Absolute camera movement, solves issue openworm/org.geppetto#160

### CODE REVIEW

**Comment by tarelli** [comment]
Reviewing this during this sprint for next release 0.2.7

**Comment by tarelli** [comment]
@felipetavares thanks for this, very good progress! I'm seeing some unexpected results, see the following: first I put the camera in a given configuration:
screen shot 2015-10-05 at 11 42 15

then I check the last two entries in the console to know what is the current absolute position/rotation
```
G.setCameraPosition(-326.81847060567185,16.866440414993235,53.06968876744922)
G.setCameraRotation(-1.1642390185776943,-1.033358504980245,-2.6702218097851396)
```
Then I reset the camera and paste those two lines in the console, expecting the camera to go back where it was, instead I get this:
screen shot 2015-10-05 at 11 42 33
Seems like the setCameraRotation is not having an effect. Any ideas? I think we are close! Thanks :)

**Comment by felipetavares** [comment]
I believe I have found the problem. In [TrackballControl:L272](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/vendor/TrackballControls.js#L272) which is inside the TrackballControl's **update** method, we read:

```
_this.object.lookAt( _this.target );
```

`_this.object` in this context is the camera. In short, TrackballControl is overriding the rotation set by  setCameraRotation.

I see two solutions.

1. Make setCameraRotation also set the TrackballControl's `target` vector from the rotation. This has a problem, which is: we would loose information, because the value we put in `target` could be different from the one that was there, as there is no 1:1 mapping between the `target` and the rotation. This would possibly cause the TrackballControl to behave differently/wrongly.

2. Instead of setCameraPosition/setCameraRotation have a setCameraPosition/setCameraTarget pair, which I hope would restore the TrackballControl's state correctly.

**Comment by tarelli** [comment]
@felipetavares what object is target? A vector?

**Comment by felipetavares** [comment]
@tarelli THREE.Vector3

**Comment by tarelli** [comment]
@felipetavares ok, could you try what I was trying to do if we use the target vector instead?

**Comment by felipetavares** [comment]
@tarelli Sure.

**Comment by tarelli** [comment]
@felipetavares thanks!

**Comment by felipetavares** [comment]
@tarelli It's working! But with a setCameraUp instead of setCameraTarget, because:

after some research in TrackballControl's code I found the key for the camera's rotation: a vector called **up** that is a camera's attribute, not a TrackballControl's one.

Also changed the code to only log position/up vector when the camera stops moving, not immediately after a mouse/touch/scroll event (because sometimes the camera is left drifting after an event, so if we logged immediately we would get the wrong camera state).

**Comment by tarelli** [comment]
@felipetavares great job Felipe, I'll check it this morning :)

**Comment by tarelli** [comment]
@felipetavares rotation seems to work but position not as much now, check this out:
screen shot 2015-10-06 at 11 25 10
in the console we have 
```
G.setCameraPosition(549.0397385499623,167.1286436883922,694.835516085354)
G.setCameraRotation(-0.4178437552905898,0.908468947833306,-0.009527171001988634)
```
but after resetting plus pasting those two lines I get this:
screen shot 2015-10-06 at 11 25 40
Does the above work for you?
Note that locally I renamed the method setCameraUp to setCameraRotation, regardless of the internal operations we are doing I think it's still a more meaningful API command for the user.
Also great what you did with waiting for the camera to be placed before updating the console, could we do the same thing when using the mouse wheel? At the moment using it for zoom floods the console with setCameraPosition commands. What do you think?

**Comment by felipetavares** [comment]
@tarelli I did a superficial research, it appears that the problem isn't setting the position but logging it. When I manually read the position it is not the reported one - and it appears to differ specially when we use the scroll.

**Comment by tarelli** [comment]
@felipetavares any more insights? What do you suggest we do?

**Comment by felipetavares** [comment]
@tarelli I am just finishing up what I believe is the definitive solution (expect it in half an hour). Spoiler: I was missing a very simple fact...

**Comment by felipetavares** [comment]
@tarelli Indeed, there was a problem with both scrolling and logging positions/rotations. After I fixed this, I noticed I was missing something pretty obvious here: We can't fully restore the state of the camera with just two 3d vectors, because it's a trackball, so we need at least one more scalar.

This was causing the problem you saw there: as long as the center of the trackball isn't moved, everything is fine, but when you move it the camera isn't restored perfectly.

Of course we *could* restore the camera to a state where it seemed to be the same, but we would have to guess where to put the trackball (I did this too, it works for visual-only purposes).

There are a number of possible ideas to fully restoring the camera:

* camera position, trackball's center (target), camera z angle
* trackball's center, eye vector (from the trackball's center to the camera's position), camera z angle
* camera position, camera rotation, trackball radius

I picked this last one, as it seems to be the most consistent and it is easier to understand for any API users (I hope).

I added this last value to setCameraRotation, so now we have:

```
setCameraRotation : function(rx, ry, rz, radius)
```

**Comment by tarelli** [comment]
@felipetavares great progress Felipe! I'll review tomorrow morning and let you know :)

**Comment by tarelli** [comment]
@felipetavares works like a charm, bravo! The only thing I would add is a check if the camera hasn't moved, now every time we select something (or just click on the canvas) even if the camera has not moved we are printing to the console the same coordinates over and over which generates noise. I would love to merge this PR and include it in the release I'll do today if you get a chance to fix the above which I think should be quick. Also maybe we could take only 2 decimal digits without any real loss, what do you think?
```
G.setCameraPosition(10.10,60.07,30.11)
G.setCameraRotation(0.10,0.07,3.11,610.16)
```

**Comment by felipetavares** [comment]
@tarelli Working on this now. I'll check if two digits are enough, if they are, expect the coordinate logging to be immediate (it's taking that long because I'm checking a lot of digits right now).

**Comment by tarelli** [comment]
@felipetavares :+1:

**Comment by felipetavares** [comment]
@tarelli With 2 decimal digits I could see bit of difference, 3 seemed good. Fixed the "click problem".
Maybe later add an API entry to set how many decimal digits to use?

**Comment by tarelli** [comment]
@felipetavares great, testing right away!

**Comment by tarelli** [comment]
@felipetavares merged :8ball:  Thank you Felipe, very useful contribution! I only had to revert a change that appeared on some files where the string "NOTE:" became "#NOTE:0" for some reason, don't know if you executed any script? Anyway I took care of it :) I have an idea for something I think you would find fun next, I can either put it on a card or we can have a meeting and chat about it if you're up for it, whichever way you prefer!

**Comment by felipetavares** [comment]
@tarelli Looks like something the Atom Imdone may have done... I'll disable it when working on Geppetto, and I think a card is better.

**Comment by tarelli** [comment]
@felipetavares :+1:

**Pull request merged**
