### PR TITLE
bump jquery ui version

### PR DESCRIPTION
**Pull request by adrianq**
- [ ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
- [ ] Make sure both push and pr travis builds are passing before asking for a review

### CODE REVIEW

**Comment by tarelli** [comment]
@mattearnshaw Hey Matt could you smoke test this? The tests passed just a visual inspection everything is sound would be helpful. The old dependency seem to have disappeared.

**Comment by adrianq** [comment]
@mattearnshaw if you are gonna give it a try, you will have to checkout this branch, remove build and node_modules, npm install and npm build-no-devTests. It looks like they have released a new version of jquery-ui and a fresh geppetto installation fails unless we update to the lastest

**Comment by mattearnshaw** [comment]
@tarelli seems fine. I tried out the stuff that I know to be using jquery-ui: tooltips, spotlight autocomplete, widget positioning. can't see any problems

**Comment by tarelli** [comment]
Thanks @mattearnshaw !

**Pull request merged**
