### PR TITLE
fix persistence of colorbar by persisting function instead of data

### PR DESCRIPTION
**Pull request by mattearnshaw**
- [ ] Run [CoreTests.js Casper Tests](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/pages/tests/casperjs/README.md), make sure they all pass, attach screenshot
- [ ] Run [UITests.js Casper Tests](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/pages/tests/casperjs/README.md), make sure they all pass, attach screenshot
- [ ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

### CODE REVIEW

**Comment by mattearnshaw** [comment]
colorbar should be stateless anyway?

**Comment by tarelli** [comment]
@mattearnshaw check if the color bar is still stateless? https://github.com/OpenSourceBrain/geppetto-osb/blob/development/ComponentsInitialization.js#L694

**Comment by tarelli** [comment]
@mattearnshaw is the colorBar still stateless?

**Comment by mattearnshaw** [comment]
yes, stateless so closing this.

**Pull request closed without merging**
