### PR TITLE
Button bar widget prototype

### PR DESCRIPTION
**Pull request by borismarin**
- ButtonBarWidget: Still needs polishing to do, but it should be usable by now. 
- Added initial support for org.geppetto.frontend.icons
- Widgets.js: Added some methods for handling size, placement
- Node.js: added method to get nodes by domain type (partially closes openworm/org.geppetto.model.neuroml#63)

### CODE REVIEW

**Comment by tarelli** [comment]
@borismarin @adrianq I get an error with this branch when loading the first sample from the dev branch:
screen shot 2015-04-24 at 14 52 13

**Comment by tarelli** [comment]
@borismarin @adrianq it was my problem, nothing has been broken by this and the widget works!

**Comment by tarelli** [comment]
@borismarin before I update this please update documentation :)
- [ ] Add widget to list
- [ ] Add one page for the widget with instructions for how to use it
http://docs.geppetto.org/en/latest/usingwidgets.html

**Comment by borismarin** [comment]
Of course it does.
=p

**Comment by borismarin** [comment]
One thing that is not ready is error handling (undefined behaviour if the
user passes broken json). I guess we can json-schema our way out, but no
time to do that now.

**Pull request merged**
