### PR TITLE
Issue #9: Message compression and queuing of scene updates

### PR DESCRIPTION
**Pull request by frenkield**
This fork provides a new messaging implementation that improves the rate of message transmission from Geppetto to the browser. The performance improvements are provided two ways:

1. Message compression: The message sender can optionally compress messages above a certain size. This implementation uses gzip for compression.
2. Asynchronous transmission: Certain messages (e.g. scene updates) are queued. Separate threads handle message processing and transmission.

The message sender is configured via spring in `org.geppetto.frontend/src/main/webapp/WEB-INF/spring/app-config.xml`.

Compression is enabled by default. The parameter `minMessageLengthForCompression` specifies the minimum message size for compression. Messages smaller than this size are not compressed. The default is 20000 bytes.

The configuration also specifies which messages should be queued (and thus processed asynchronously). The default configuration queues only 1 message: `scene_update`. All other messages are processed synchronously. This means that control messages (e.g. pause scene) are delivered immediately. So the UI remains responsive regardless of how many scene updates are waiting to be processed/transmitted.

When adding a new message (scene update) to the queue the message sender blocks by default. The message sender can also be configured to discard messages when the queues are full. In this case, the oldest message (front of the queue) is discarded and the new message is added. Message discarding allows a scene to progress more quickly and can be more visually appealing. However, messages are lost and this may disrupt any processing done by the client.

The message sender class is called `DefaultMessageSender`. That's probably not the greatest name. Please let me know if you'd like me to change that - or anything else for that matter.

Thanks!
David Frenkiel

### CODE REVIEW

**Comment by gidili** [comment]
Thanks for the effort @frenkield! Will review this with @tarelli and let you know. There is a big refactoring going on in the datamanager branch of most geppetto bundles and this will go in after that stuff is ready (hopefully end of this week), but we can start to review and give feedback in the meanwhile!

**Comment by tarelli** [comment]
@frenkield working like a charm, will merge soon, great work David!

**Comment by tarelli** [comment]
@frenkield after some more testing I've noticed a weird behaviour once you leave the simulation running for a while with the first sample (the sphere). At the beginning everything is very smooth and fast, however after around 30 seconds that the simulation is running the updates begin to stutter and heavy latency takes over. Might be some buffer getting filled up? Does it happen to you? Thanks!

**Comment by frenkield** [comment]
@tarelli, yeah I'm seeing that as well. I'll take a look.

**Comment by frenkield** [comment]
@tarelli, it looks like the stuttering is caused by message decompression overhead in the browser. That scene grows steadily by about 140 bytes per update. So after 30 seconds the uncompressed scene size is over 200k and the decompression overhead becomes increasingly noticeable. Is that scene supposed to grow  steadily in size over time?

**Comment by tarelli** [comment]
@frenkield no, it's not supposed to, need to check why it's happening

**Comment by tarelli** [comment]
@frenkield I found the issue which is unrelated to this PR, a new element for time is added at each timestep rather than being changed, see screenshot here 
screen shot 2015-05-31 at 14 48 38 cc @jrmartin 
Another issue that I noticed is that the as we are using GSon to serialize the transport message `String message = new Gson().toJson(transportMessage);` the JSON objects that were built by our visitors (and stored inside the data field of the GeppettoTransportMessage) are considered string and therefore re-escaped (hence all the backslashes we see in the files) while they were already JSON ready. Both these issues are independent of this PR but I'll wait for at least the first one to be fixed before merging this. I'll update this once I'll chat with @jrmartin about the above, thanks for investigating David!

**Comment by frenkield** [comment]
Ok sounds good. Thanks, @tarelli.

**Comment by tarelli** [comment]
@jrmartin has fixed this in the data manager branch, I will merge this PR in both development and datamanager branch (which will soon become development)

**Comment by tarelli** [comment]
Merged into development, now I'll merge it also in the datamanager branch

**Comment by tarelli** [comment]
@frenkield I merged this into datamanager, now we have compression in the latest codebase! If you have a chance to review this merge https://github.com/openworm/org.geppetto.frontend/commit/a1a64ac867fbdd150b06b23bef2add29971cf5c6 to make sure I didn't mess anything it would be helpful :) As you will notice quite few things have changed in the latest (including some classes being renamed/removed like GeppettoServletController->ConnectionHandler and GeppettoMessageInbound->WebsocketConnection) but I just tested and it seems to be working. When you have some time I'd like to walk you through how things are working in the datamanager branch, the plan is to merge it back into development within the month. Thanks again for this contribution!

**Comment by frenkield** [comment]
Ok great, I'll take a look. Maybe we can do a call early next week.

**Comment by frenkield** [comment]
@tarelli, I'm having some trouble getting the `datamanager` branch to run.

I used the utilities under org.geppetto to deploy the `datamanager` branch of every project to Geppetto 0.2.3. Is that correct?

I'm seeing this error:

Installation of plan 'multi-artifact.plan' version '1.0.0' failed. org.eclipse.virgo.nano.deployer.api.core.DeploymentException: Unable to satisfy dependencies of bundle 'multi-artifact.plan-1-org.geppetto.frontend' at version '0.2.3': A library with the name 'org.springframework.spring' and a version within the range '[3.1.3.RELEASE, oo)' could not be found

**Comment by tarelli** [comment]
@frenkield in the datamanager branch we upgraded to spring 3.1.3 to fix some bugs of the spring framework we found. We haven't yet updated the documentation and the scripts which will account for the following:
go to /virgo_folder/repository/ext and delete org.springframework.* then extract there the content of [this archive](https://dl.dropboxusercontent.com/u/7538688/spring3.1.3.zip) to put there the new version. We'll be merging to development in the next week or so, note that the branch is currently under heavy development and a lot has changed. Which day would work for you for a hangout this week? It would be helpful if I could walk you through how things work now so that you won't feel disoriented :)

**Comment by frenkield** [comment]
Thanks, @tarelli. I'll do the spring update.

Wednesday, Thursday or Friday at 7am New York time works for me.

**Pull request merged**
