### PR TITLE
Feature/vfb new layout2 canvas fixes

### PR DESCRIPTION
**Pull request by jrmartin**
- [ ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend
- [ ] Make sure both push and pr travis builds are passing before asking for a review

### CODE REVIEW

**Comment by tarelli** [comment]
@jrmartin what is this fixing? cc @ddelpiano

**Comment by jrmartin** [comment]
@tarelli This one fixes the stack viewer images not been centered on the vfb flex layout. Also, it reverted the changes made for canvas selection on VFB that were causing trouble on the default projects. 

The branch is not going to be merge to development, but to vfb_new_layout2, and last I spoke to @ddelpiano  he fixed the stackviewer issue another way. The only remaining thing to check would be the current state of ThreeDEngine.js don't break the selection on default projects. 

We can probably close this without merging, but also a good idea to keep it open until we know for sure vfb_new_layout2's ThreeDEngine selection is good for core projects.

**Comment by tarelli** [comment]
@jrmartin thanks for the update, @ddelpiano let me know if this one is needed

**Comment by ddelpiano** [comment]
@tarelli this is what I was saying this morning :), it is fine to leave this out since these changes are already inside the flexlayout branch.

**Pull request closed without merging**
