### PR TITLE
New htmlviewer component, fixings in dicom viewer and tree component and improve parametrization in Awidget

### PR DESCRIPTION
**Pull request by adrianq**
- [ ] Run [CoreTests.js Casper Tests](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/pages/tests/casperjs/README.md), make sure they all pass, attach screenshot
- [ ] Run [UITests.js Casper Tests](https://github.com/openworm/org.geppetto.frontend/blob/master/src/main/webapp/js/pages/tests/casperjs/README.md), make sure they all pass, attach screenshot
- [ ] Add coverage for whatever new functionality, to a JUnit test if it's backend, to a Casper Test if it's frontend

### CODE REVIEW

**Comment by adrianq** [comment]
@tarelli Ready to be merged. This PR implements a few things:
- DicomViewer: Refresh state on data change
- HTMLViewer: New component. Very simple component that aims to substitute current Popup component. At the moment it is just a div with some styles but, among other things, can be instantiated in a react way. Tests will be implemented as part of [this card](https://github.com/openworm/org.geppetto/issues/563)
- TreeViewer: Move some logic inside the PR. Better click handling. Better styling. Shorter labels.
- AWidget: I have added a bunch of parameter as react props (resizable, draggable, position, etc). I have also added fixPosition props. If true, after render widget dom element will be moved to its original container.  Once moved, widget will behave properly on window resize. Therefore, the main target of this prop is scenario where we want a dialog container that cannot be moved or resize.
- Widget: Minor change to remove unneeded variable.

Find below an example of how widgets can be instantiated now:
```
render() {
            if (window.Instances == undefined) {
                return (<div></div>);
            }

            var TreeWidget = addWidget(TreeHM);
            var DicomViewerWidget = addWidget(DicomViewer);
            var HTMLViewerWidget = addWidget(HTMLViewer);

            return (
                <div id="DataPortalSection" style={{ position: 'relative' }}>
                    <TreeWidget
                        id="TreeContainer"
                        name={"Tree"}
                        componentType={'TREE'}
                        treeData={this.treeData}
                        size={{ height: DataPortalSectionUtils.default_height, width: DataPortalSectionUtils.column_width }}
                        position={{ left: DataPortalSectionUtils.left_first_column, top: DataPortalSectionUtils.top }}
                        ref="tree"
                        onClickVisualize={this.handleClickVisualize}
                        resizable={false}
                        draggable={false}
                        fixPosition={true}
                        showHistoryIcon={false}
                        closable={false}
                        minimizable={false}
                        collapsable={false}

                    />

                    <HTMLViewerWidget
                        id="HTMLViewerContainer"
                        name={"HTMLViewer"}
                        componentType={'HTMLViewer'}
                        content={""}
                        size={{ height: DataPortalSectionUtils.default_height, width: DataPortalSectionUtils.column_width }}
                        position={{ left: DataPortalSectionUtils.left_second_column, top: DataPortalSectionUtils.top }}
                        ref="htmlViewer"
                        resizable={false}
                        draggable={false}
                        fixPosition={true}
                        showHistoryIcon={false}
                        closable={false}
                        minimizable={false}
                        collapsable={false}
                    />

                    <DicomViewerWidget
                        id="DicomViewerContainer"
                        name={"Dicom Viewer 2"}
                        mode={'quad_view'}
                        componentType={'DICOMVIEWER'}
                        size={{ height: DataPortalSectionUtils.default_height, width: DataPortalSectionUtils.column_width_2x }}
                        position={{ left: DataPortalSectionUtils.left_third_column, top: DataPortalSectionUtils.top }}
                        ref="dcmv"
                        resizable={false}
                        draggable={false}
                        fixPosition={true}
                        showHistoryIcon={false}
                        closable={false}
                        minimizable={false}
                        collapsable={false}
                    />
                </div>
            );
        }
```

**Comment by adrianq** [comment]
@tarelli To decouple addWidget from AWidget is not that simple. The class depends on the WrappedComponent passed as an attribute. [See](https://github.com/openworm/org.geppetto.frontend/blob/e23755751ad28d6f7c63ec300e2e991b0c7046f8/src/main/webapp/js/components/widgets/AWidget.js#L20) I can maybe rename the class to something like WidgetCapabality so we then can do WidgetCapability.createWidget

**Comment by adrianq** [comment]
@tarelli I have changed AWidget into WidgetCapability as I mentioned before.

Test executed. Four errors:
screenshot from 2017-07-23 14-42-43
screenshot from 2017-07-23 14-43-04

Three of them were already identified as unstable. After a bit of debugging, I have realised the fourth one (the opacity one) is also an unstable one. I have added it [here](https://github.com/openworm/org.geppetto.frontend/issues/634). I guess the error has to do with this.setThreeColor failing a few lines before. Whenever this test passes, I don't have this error.

Ready to be merged!

**Comment by jrmartin** [comment]
@adrianq Good to see you are getting those too. I though I was the only one, they are unstable as you pointed out, I have fixed them in the branch change-casperjs_port already.

**Pull request merged**
